name: Publish package to GitHub Packages

on:
  release:
    types: [created]

env:
  MAJOR_VERSION: 0
  MINOR_VERSION: 0

jobs:
  publish:
    runs-on: ubuntu-latest 
    container: wpilib/roborio-cross-ubuntu:2022-18.04
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - name: Publish package
        run: ./gradlew build -PprojVersion=${{ github.ref_name }} publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}